- module_example/TrkEval.cxx
- module_example/TrkEval.h
- packages/global_consts/GlobalConsts.h
- packages/ktracker/KalmanFastTracking.cxx
Fixed a bug in extrapolation from station 1 to FMag front face.
Previously there are inconsistency of the field setting in global.h and in the adapted ktracker code.
Made them consistent this time.
Before fix 1k DY, no target field:
After fix 1k DY, no target field:
Next step would be implementing the extrapolation with target field on.
> Fixed extrapolation through FMag - field inconsistency issue

- packages/ktracker/KalmanFastTrackingWrapper.cxx
- packages/ktracker/KalmanPrgTrk.cxx
- packages/ktracker/KalmanPrgTrk.h
- simulation/g4detectors/DPDigitizer.cc
- simulation/g4detectors/DPDigitizer.h
Hide some functions in `DPDigitizer` from CINT to prevent error msg in ROOT dictionary generation.
Thanks to Mindy for pointing this out!
Sorry this PR also has some update in the `KalmanFastTrackingWrapper` for dev purpose.
> Small fix: hide some functions from CINT

- online/chan_map/CMakeLists.txt
Thanks for this update. I noticed one thing that this package won't compile with ROOT5. For the `tuple` class template could not be used in ROOT5 interpreter. I suggest to make a change in this pull request to skip the ROOT dictionary generation for ROOT5.
> Compile under ROOT5

- build.sh
- macros/Fun4MainDaq.C
- online/chan_map/CMakeLists.txt
- online/chan_map/ChanMapper.cc
- online/chan_map/ChanMapper.h
- online/chan_map/ChanMapperRange.cc
- online/chan_map/ChanMapperRange.h
- online/chan_map/ChanMapperScaler.cc
- online/chan_map/ChanMapperScaler.h
- online/chan_map/ChanMapperTaiwan.cc
- online/chan_map/ChanMapperTaiwan.h
- online/chan_map/ChanMapperV1495.cc
- online/chan_map/ChanMapperV1495.h
- online/chan_map/DbSvc.cc
- online/chan_map/DbSvc.h
- online/chan_map/LinkDef.h
- online/chan_map/macros/CheckChanMap.C
- online/chan_map/macros/MakeChanMap.C
- online/chan_map/macros/UploadChanMap.C
- online/decoder_maindaq/CMakeLists.txt
- online/decoder_maindaq/DecoParam.cc
- online/decoder_maindaq/DecoParam.h
- online/decoder_maindaq/MainDaqParser.cc
- packages/db_svc/CMakeLists.txt
- packages/db_svc/DbSvc.cc
- packages/db_svc/DbSvc.h
- packages/db_svc/LinkDef.h
- setup-e1039-core.sh
I added several classes (like ChanMapperTaiwan) for the channel mapping.  These classes can read the mapping info from MySQL DB, as well as writing to DB and also reading/writing tsv file.  They can handle multiple mappings for multiple run ranges.  I updated the MainDAQ decoder to use these new classes.
I also added a class (DbSvc) for the database service.  For now it is used by only the channel-mapping classes, but I expect all other classes can/should use it because of the following advantages;
* The host, user and password are defined and switchable.
* The password is kept outside the git repository.
* Functions to create and drop schema and table are defined.
Details will be presented at the coming meeting, but this branch can be safely merged as the changes don't interfere with the …
> Channel mapping and database service

- framework/phool/recoConsts.cc
- generators/phhepmc/CMakeLists.txt
- packages/global_consts/GlobalConsts.h
- packages/jobopts_svc/JobOptsSvc.cxx
- packages/ktracker/EventReducer.cxx
- packages/ktracker/FastTracklet.cxx
- packages/ktracker/FastTracklet.h
- packages/ktracker/Fun4AllSRawEventInputManager.cxx
- packages/ktracker/Fun4AllSRawEventInputManager.h
- packages/ktracker/Fun4AllSRawEventInputManagerLinkDef.h
- packages/ktracker/KalmanDSTrk.cxx
- packages/ktracker/KalmanFastTrackingWrapper.cxx
- packages/ktracker/KalmanFastTrackingWrapper.h
- packages/ktracker/SRawEvent.cxx
- packages/ktracker/SRawEvent.h
- packages/ktracker/SRecEvent.cxx
- simulation/g4gdml/CMakeLists.txt
- new `Fun4AllSRawEventInputManager` to read in E906 decoded data in SRawEvent format
- bug fix for left-right resolving: removed a previous workaround
-  due to possible geometry in-consistency, L-R resolving was not working for sim data initially
-  now it works on sim data and the sign of driftDistance removed before tracking
- try to use the `recoConst` to substitute the macros used in 'GlobalConsts.h'
- now only substituted the `KMAGSTR` var
Now standalone ktracker and the e1039 ktracker yield same results:
Also the e1039 ktracker has a very high reconstruction efficiency with pure simulated muons:
> Fun4AllSRawEventInputManager, L-R resolving bug fix and introducing the recoConst

- build.sh
- macros/Fun4MainDaq.C
- macros/OnlMon4MainDaq.C
- online/onlmonserver/CMakeLists.txt
- online/onlmonserver/LinkDef.h
- online/onlmonserver/OnlMonCanvas.cc
- online/onlmonserver/OnlMonCanvas.h
- online/onlmonserver/OnlMonCham.cc
- online/onlmonserver/OnlMonCham.h
- online/onlmonserver/OnlMonClient.cc
- online/onlmonserver/OnlMonClient.h
- online/onlmonserver/OnlMonClientLinkDef.h
- online/onlmonserver/OnlMonMainDaq.cc
- online/onlmonserver/OnlMonMainDaq.h
- online/onlmonserver/OnlMonMainDaqLinkDef.h
- online/onlmonserver/OnlMonServerLinkDef.h
- online/onlmonserver/OnlMonSpill.cc
- online/onlmonserver/OnlMonSpill.h
- packages/db_svc/DbSvc.cc
- packages/db_svc/DbSvc.h
I added two online-monitor classes (OnlMonSpill and OnlMonCham).  OnlMonCham is a typical example of subsystem basic monitors, which monitors the distributions of element IDs and tdcTimes.
The viewer macro (OnlMon4MainDaq.C) was also updated so as to select the monitor to be drawn, as seen in the attached screenshot.
> Onlmon client

- generators/phhepmc/CMakeLists.txt
- generators/phhepmc/Fun4AllHepMCInputManager.cc
Removed FROG for now. Full path needed for the input.
[e1039-analysis/SimChainDev/Fun4Sim.C](https://github.com/E1039-Collaboration/e1039-analysis/blob/master/SimChainDev/Fun4Sim.C#L225) updated and tested for the HepMC input/output manager.
An example txt file with 10 DY HepMC events:
/pnfs/e906/persistent/users/yuhw/examples/HepMC_txt/hepmcout.txt
> Bring back the HepMC input manager

- module_example/TrkEval.cxx
- packages/geom_svc/GeomSvc.cxx
- packages/ktracker/KalmanDSTrk.cxx
- packages/ktracker/KalmanFastTrackingWrapper.cxx
- packages/ktracker/PatternDBGen.cxx
- packages/ktracker/PatternDBGen.h
- packages/ktracker/PatternDBGenLinkDef.h
- packages/ktracker/PatternDBUtil.cxx
- simulation/g4detectors/DPDigitizer.cc
Init PatternDBGen for dedicated DSearch tracking database simulation.
Updated GeomSvc and related modules to make the simulation compatible with run6 configuration (`$E1039_RESOURCE/alignment/run6`) and @liuk 's geometry schema `user_liuk_geometry_G9_run5_2`
**Seems this schema used detector id 7-12 for the DP trigger planes.
So DC1 shifted to use 1-6. This may won't be the case in the future.**
[e1039/analysis/CODAChainDev](https://github.com/E1039-Collaboration/e1039-analysis/tree/master/CODAChainDev) and [e1039/analysis/SimChainDev](https://github.com/E1039-Collaboration/e1039-analysis/tree/master/SimChainDev) updated accordingly.
> Init PatternDBGen; Sim. compatible with run6 config

- packages/Display/interface/PHEventDisplay.cxx
- packages/Display/interface/PHEventDisplay.h
- packages/Display/modules/mTrkEveDisplay.cxx
- packages/dptrigger/DPTriggerAnalyzer.cxx
- packages/evt_filter/CMakeLists.txt
- packages/evt_filter/EvtFilter.cxx
- packages/evt_filter/EvtFilter.h
- packages/evt_filter/EvtFilterLinkDef.h
- init of Event filter `EvtFilter`
- Using `EvtFilter` to control interested event type, implemented in macro, [example](https://github.com/E1039-Collaboration/e1039-analysis/blob/master/CODAChainDev/eve_disp_dst.C)
- Add event information in the main tab of the event display
Example:
> Event display update; event filter

- packages/ktracker/CMakeLists.txt
- packages/ktracker/KalmanDSTrk.cxx
- packages/ktracker/PatternDBGen.cxx
- packages/ktracker/PatternDBUtil.cxx
Make the DSearch compatible with D1 using id 1 to 6.
Ref. [docDB#5911](https://seaquest-docdb.fnal.gov/cgi-bin/private/ShowDocument?docid=5911)
Other fix:
- small include fix for `PatternDBGen.cxx`
- library linking fix for `packages/ktracker`
> Works with D1 as 1-6; and some small fix

- module_example/TrkEval.cxx
- module_example/TrkEval.h
- packages/ktracker/SRecEvent.h
- packages/ktracker/VertexFit.cxx
- packages/ktracker/VertexFit.h
- packages/ktracker/VertexFitLinkDef.h
Ported the vertexing module `VertexFit` from E906
Based on [the R007 version](https://github.com/HaiwangYu/seaquest-ktracker/blob/R007_dev/inc/VertexFit.h)
Example usage: [here](https://github.com/E1039-Collaboration/e1039-analysis/blob/master/SimChainDev/Fun4Sim.C#L249-L250) (commented out for now)
Tested with two unlike-sign muons from -300 and -130 cm through Geant simulation with current ktracker reconstruction:
*definition of `dimu` below: `T->SetAlias("dimu","DST.SRecEvent.fDimuons")`
- Also updated the TrkEval to make it compatible with DC1 using id 1-6.
> Ported Vertexing from E906

- packages/ktracker/KalmanDSTrk.cxx
- packages/ktracker/KalmanDSTrk.h
- packages/ktracker/KalmanFastTrackingWrapper.cxx
- packages/ktracker/KalmanFastTrackingWrapper.h
- packages/ktracker/PatternDBUtil.cxx
- packages/ktracker/PatternDBUtil.h
DSearch level:
- 0 : no filter
- 1 : in-station filter
- 2: in-station + station 23 liking
```C++
KalmanFastTrackingWrapper::set_DS_level(int level)
```
Input DB file name
- sim db : raw tracks from simulation
- pattern db : `TrackletKey`
If both are set, pattern db would be used.
```C++
KalmanFastTrackingWrapper::set_sim_db_name(string name);
KalmanFastTrackingWrapper::set_pattern_db_name(string name);
```
> Update interface of DSearch

- online/decoder_maindaq/CodaInputManager.cc
- online/decoder_maindaq/DecoParam.cc
- online/decoder_maindaq/DecoParam.h
- online/decoder_maindaq/DecoStatusDb.cc
- online/decoder_maindaq/DecoStatusDb.h
- online/decoder_maindaq/DecoStatusDbLinkDef.h
- online/decoder_maindaq/MainDaqParser.cc
- online/decoder_maindaq/UtilOnline.cc
- online/decoder_maindaq/UtilOnline.h
- online/macros/Daemon4MainDaq.C
- online/macros/Fun4MainDaq.C
- online/macros/OnlMon4MainDaq.C
- online/onlmonserver/OnlMonCanvas.cc
- online/onlmonserver/OnlMonCanvas.h
- online/onlmonserver/OnlMonCham.cc
- online/onlmonserver/OnlMonClient.cc
- online/onlmonserver/OnlMonHodo.cc
- online/onlmonserver/OnlMonMainDaq.cc
- online/onlmonserver/OnlMonProp.cc
- online/onlmonserver/OnlMonServer.cc
- online/onlmonserver/OnlMonServer.h
- online/onlmonserver/OnlMonUI.cc
- online/onlmonserver/OnlMonUI.h
- online/onlmonserver/OnlMonV1495.cc
This pull request contains various types of updates that I implemented during my Fermilab stay in June & July.  I closely looked into the data taken and the behavior of the decoding process.  The updated code can be compiled fine on seaquestdaq01, and is running to auto-decode every run.
Below is the major part of these updates.
* The decoder discards all flush events that come before the 1st BOS event per run, since such events contain no hit by design and thus not useful.
* The OnlMonMainDaq monitor shows a warning message when the error rates of events or hits are high.
* The I/O access of OnlMon histograms is protected by MUTEX. Thus the OnlMon server will no longer crash when accessed frequently.
* The status of the decoder process per run (i.e. started and finished) is recorded to …
> Massive updates on the online code

- online/decoder_maindaq/CodaInputManager.cc
- online/macros/Daemon4MainDaq.C
- online/macros/Fun4MainDaq.C
- online/onlmonserver/OnlMonMainDaq.cc
- online/onlmonserver/OnlMonMainDaq.h
- online/onlmonserver/OnlMonServer.cc
- script/setup-install.sh
The online code (decoder & online monitor) was updated as follows in Aug 2019.  It is running fine on seaquestdaq01 as the online-version library (/data2/e1039/core-online).  It is not urgent but now I like to merge the updates.
1. Daemon4MainDaq.C, which starts a decoding process per run, now checks and waits until the Coda file directory is mounted.
2. The online monitor for Main DAQ (OnlMonMainDaq) shows the number of Taiwan TDC boards per event.  A deviation of this number tells us a problem on board(s).
3. The OnlMon server (OnlMonServer) rejects all client connections that come from WAN.  It has improved the security and the stability (where the server process died due to port scans multiple times in the past), although such connections should be blocked first by the firewall.
> Updates on the online code in Aug 2019

- build.sh
- online/decoder_maindaq/CodaInputManager.cc
- online/decoder_maindaq/CodaInputManager.h
- online/decoder_maindaq/DbUpSpill.cc
- online/decoder_maindaq/DbUpSpill.h
- online/decoder_maindaq/MainDaqParser.cc
- online/macros/Daemon4MainDaq.C
- online/macros/Fun4MainDaq.C
- online/onlmonserver/OnlMonClient.cc
- online/onlmonserver/OnlMonServer.cc
- online/onlmonserver/OnlMonServer.h
- packages/geom_svc/macros/CheckChanMap.C
- packages/geom_svc/macros/MakeChanMap.C
- packages/geom_svc/macros/UploadChanMap.C
- script/setup-install.sh
A big issue about the MainDAQ decoder is that a decoder process sometimes (once per day) gets stuck and never ends.  I made several small updates, and here I request a pull because this new version is running without problem in the past few days.
I would expect this version doesn't conflict with PL 57.  But if it is found conflicting after PL 57 is merged, please just let me know it so that I resolve it.
I think the last update did fix the issue.  The Mutex variable in `OnlMonServer` had not been initialized well (although it was how the original example did), which sometimes caused a never-ending wait when `OnlMonClient::process_event()` called `pthread_mutex_lock()`.
Below are the other updates included in this request, which are likely not related to the issue but are helpful anyway. …
> Updates for better stability of MainDAQ decoder.

- packages/Display/interface/PHEventDisplay.cxx
The title says it all.  I tried various combinations of function calls in PHEventDisplay::draw_default() and the present one works fine.
I would ask Abi to test this updated version so that he can start learning the source code and the macro of the event display.
> The 3D event display now keeps its view point when moving to next event

- README.md
- build.sh
- generators/phhepmc/CMakeLists.txt
- interface_main/CMakeLists.txt
- interface_main/SQParamDeco.h
- interface_main/SQParamDeco_v1.h
- online/decoder_maindaq/CodaInputManager.cc
- online/decoder_maindaq/CodaInputManager.h
- online/decoder_maindaq/DbUpRun.cc
- online/decoder_maindaq/Fun4AllEVIOInputManager.cc
- online/decoder_maindaq/MainDaqParser.cc
- online/decoder_maindaq/MainDaqParser.h
- online/onlmonserver/OnlMonClient.cc
- online/onlmonserver/OnlMonHodo.cc
- packages/PHField/CMakeLists.txt
- script/setup-install.sh
- script/this-core-org.sh
I first fixed a problem (bug) that happens when a run fails at starting. It happened in runs 1065, 1067 and 1069.  This updated version is already running on seaquestdaq01, and the problem never happens since then.
I updated `script/this-core-org.sh`.  It now cleans up the environmental variables (like `PATH` and `ROOT_INCLUDE_PATH`) when `E1039_CORE` is already defined.  The similar change has been made on `this-share.sh` in the e1039-share package.  As a result, we can change the E1039_* environment at any time, by executing `this-core.sh` or `this-e1039.sh`.  This update will help Abi and me to test PR 63 (and future updates).
> Online bug fix.  Better handling of environmental variables.

- online/decoder_maindaq/DecoData.cc
- online/decoder_maindaq/DecoData.h
- online/decoder_maindaq/MainDaqParser.cc
- online/macros/TestOnlMon4MainDaq.C
- online/onlmonserver/AnaWait.cc
- online/onlmonserver/AnaWait.h
- online/onlmonserver/CMakeLists.txt
- online/onlmonserver/LinkDef.h
- online/onlmonserver/OnlMonCanvas.cc
- online/onlmonserver/OnlMonCanvas.h
- online/onlmonserver/OnlMonCham.cc
- online/onlmonserver/OnlMonClient.cc
- online/onlmonserver/OnlMonClient.h
- online/onlmonserver/OnlMonComm.cc
- online/onlmonserver/OnlMonComm.h
- online/onlmonserver/OnlMonH4.cc
- online/onlmonserver/OnlMonH4.h
- online/onlmonserver/OnlMonHodo.cc
- online/onlmonserver/OnlMonHodo.h
- online/onlmonserver/OnlMonMainDaq.cc
- online/onlmonserver/OnlMonProp.cc
- online/onlmonserver/OnlMonReco.cc
- online/onlmonserver/OnlMonServer.cc
- online/onlmonserver/OnlMonServer.h
- online/onlmonserver/OnlMonTrigNim.cc
- online/onlmonserver/OnlMonTrigSig.cc
- online/onlmonserver/OnlMonUI.cc
- online/onlmonserver/OnlMonUI.h
- online/onlmonserver/OnlMonV1495.cc
- packages/UtilAna/UtilSQHit.cc
This update mainly adds a function to the OnlMon viewer that selects a set of spills to be monitored.  The updated version is already in use after it was tested on e1039-monitor by Abi and me last week.
This update also includes other small changes;
- A new plot was added to OnlMonHodo.
- OnlMonServer::HandleConnection() now ignores unexpected message (rather than gets stuck).
- The decoder (MainDaqParser) now ignores the spill-counter event so that spill ID is always set by the internal counter.  Details can be found in elog #1687.
- The bug in UtilSQHit::FindFirstHits() was fixed, as done in e1039-analysis.
Below is technical details about the spill selector.
An OnlMon hist is filled at the side of OnlMon server.  Individual OnlMon clients (such as OnlMonHodo) need not check when new …
> Addition of spill selector to OnlMon

- online/decoder_maindaq/DbUpSpill.cc
- online/macros/Fun4MainDaq.C
- online/macros/OnlMon4MainDaq.C
- online/onlmonserver/OnlMonCham.cc
- online/onlmonserver/OnlMonHodo.cc
- online/onlmonserver/OnlMonHodo.h
- online/onlmonserver/OnlMonProp.cc
- online/onlmonserver/OnlMonV1495.cc
- online/onlmonserver/OnlMonV1495.h
- script/setup-install.sh
The DP hodoscope was added to the channel mapping, since its readout was included in Main DAQ and its mapping was provided by Kun.  `Fun4MainDaq.C` now calls `GeomSvc::UseDbSvc(true)`
in order to fetch the latest geometry info (particularly the number of elements per DP-hodo plane).
It was also included in the online monitor.  It is taken care of by `OnlMonHodo` as one of the hodoscope groups.  I took this chance to change the way of selecting detector IDs to be monitored, where detector IDs were hard-coded in the past.
This new version is already running on seaquestdaq01.  Thus I would ask Abi to just review the changes and make a merge.  I think he need not compile nor run this version.
> Addition of DP hodoscope to channel mapping and online monitoring

- framework/fun4all/Fun4AllDstOutputManager.cc
- framework/fun4all/Fun4AllDstOutputManager.h
- online/decoder_maindaq/DecoError.cc
- online/decoder_maindaq/DecoError.h
- online/decoder_maindaq/DecoParam.cc
- online/decoder_maindaq/DecoParam.h
- online/decoder_maindaq/Fun4AllEVIOInputManager.cc
- online/decoder_maindaq/Fun4AllSpillDstOutputManager.cc
- online/decoder_maindaq/Fun4AllSpillDstOutputManager.h
- online/decoder_maindaq/Fun4AllSpillDstOutputManagerLinkDef.h
- online/decoder_maindaq/MainDaqParser.cc
- online/decoder_maindaq/MainDaqParser.h
1.
Several errors found by the MainDAQ decoder are so critical that shift crew should notice them.
Here I introduced a new interface for it, where "IntegrityWatch.py" took care of it in E906.
A new class, "DecoError", holds errors found by MainDaqParser and uploads them to DB (once per spill).  The uploaded info is parsed and drawn the DAQ Status Monitor, which is out of e1039-core.
2.
The size of one DST file could be too large for several purposes such as the track reconstruction on grid.  I created a new Fun4All output manager, "Fun4AllSpillDstOutputManager", which creates one DST file per 10 spills.  The number, 10, is adjustable.
```
ls /data2/e1039/dst-devel/spill/run_001685
run_001685_spill_000000000_spin.root
run_001685_spill_000000010_spin.root …
```
> Interface of error checker in MainDAQ decoder / Creation of spill-by-spill DST files

- build.sh
- online/macros/Fun4MainDaq.C
- online/macros/OnlMon4MainDaq.C
- online/macros/TestOnlMon4MainDaq.C
- online/onlmonserver/OnlMonClient.cc
- online/onlmonserver/OnlMonClient.h
- online/onlmonserver/OnlMonComm.cc
- online/onlmonserver/OnlMonComm.h
- online/onlmonserver/OnlMonServer.cc
- online/onlmonserver/OnlMonServer.h
- online/onlmonserver/OnlMonUI.cc
- packages/UtilAna/UtilHodo.cc
OnlMonClient is now capable of disabling spill-by-spill histograms. This new function is useful when the number of spill per run is too many (i.e. in weekend run) and also the decoder is executed in the offline mode.
As additional changes; "build.sh" can now resume building packages when "-r" option is used.  Bugs in UtilHodo were fixed.
> Function to disable spill-by-spill histograms in OnlMonClient.

- build.sh
1. added a -i option to allow build incrementally. It is essentially the -s option without deleting the existing build directory;
2. added a -c option to pass additional options to the cmake
3. for all build modes, the script will attempt to delete the installation files from the previous build to guarantee the new headers/libraries will be installed
changes 1 and 2 do not change the existing behavior; change 3 does change the existing behavior of the script but should be transparent to user.
> 3 small changes to the build script which I found useful in the development

- simulation/g4dst/LinkDef.h
- simulation/g4dst/RequireParticlesInAcc.cc
- simulation/g4dst/RequireParticlesInAcc.h
A new SubsysReco module, "RequireParticlesInAcc", is a selector that saves an event into DST only when two (or more) particles in the event go into the acceptance.  It can be activated easily via `se->registerSubsystem(new RequireParticlesInAcc())` in `Fun4Sim.C` etc.
It reduces the size of DST files largely.  Below are results of 10k J/psi event generations without and with "RequireParticlesInAcc":
* Without:  288 MB, 10,000 events in DST, 77 minutes for process
* WIth     :      4 MB,        72 events in DST, 72 minutes
So the size becomes ~1%, where the reduction should be weaker when D-Y (i.e. higher-mass) event is generated. 
The process time does not change much as seen above, because most of the time are spent on the Geant part.  It cannot be skipped since "RequireParticlesInAcc" …
> Generation of in-acceptance events

- packages/PHField/PHFieldConfig_v3.cc
- packages/reco/SQGenFit/GFTrack.cxx
- packages/reco/interface/FastTracklet.cxx
- packages/reco/interface/FastTracklet.h
- packages/reco/interface/FastTrackletLinkDef.h
- packages/reco/interface/SRecEvent.h
- packages/reco/ktracker/KalmanFastTracking.cxx
- packages/reco/ktracker/SQReco.cxx
- packages/reco/ktracker/SQReco.h
This PR contains three changes:
1. address the genfit exception reported by Abi, by adding exception handling when calling the genfit track extrapolation function. When the exception happens, for now only an error message is printed on stderr, and the related chisq of the track is set to 999., whether we should discard this track is left to be decided in the later stage (identified by chisq=999.)
2. fixed a bug in the tracklet global constant initialization - previously the global constants like KMAGSTR is only initialized to default value in the scope of `FastTracklet.cxx`
3. added an option to save the list of final track candidates (Tracklet with stationID=7) on the DST tree as well. To achieve that, following changes are made (`RecoE1039Sim.C` macro is updated accordingly in …
> Bug fix in Genfit integration 

- packages/PHField/CMakeLists.txt
- packages/PHField/PHField.h
- packages/PHField/PHField3DCartesian.cc
- packages/PHField/PHField3DCartesian.h
- packages/PHField/PHFieldSeaQuest.cc
- packages/PHField/PHFieldSeaQuest.h
- packages/PHField/SQField3DCartesian.cc
- packages/PHField/SQField3DCartesian.h
- packages/PHField/utils/convert.cxx
- packages/geom_svc/GeomSvc.cxx
- simulation/g4detectors/PHG4DetectorSubsystem.cc
- simulation/g4detectors/PHG4DetectorSubsystem.h
- simulation/g4main/G4TBMagneticFieldSetup.cc
- simulation/g4main/G4TBMagneticFieldSetup.hh
- simulation/g4main/PHG4PhenixDetector.cc
- simulation/g4main/PHG4PhenixDetector.h
- simulation/g4main/PHG4PhenixSteppingAction.cc
- simulation/g4main/PHG4PhenixSteppingAction.h
- simulation/g4main/PHG4Reco.cc
- simulation/g4main/PHG4Reco.h
- simulation/g4main/PHG4Subsystem.h
This PR consists of 2 parts: the first one is to fix a bug in the `PH3DFieldCartisian` class which was used for the field map interpolation in our core software; the second one is to improve the speed of G4 simulation via several changes. The original purpose of the PR was only to improve the simulation speed, however during the process I noticed the bug in the field map which caused the momentum reconstruction to be off by ~1%.
In the current core software, the KMag and FMag are implemented by `packages/PHField/PHField3DCartesian`. This class read the text-based input grid file (contains x/y/z/Bx/By/Bz), save the content in a map using (x, y, z) as key and (Bx, By, Bz) as value. To obtain the magnetic field strength at a spacepoint (x, y, z), this class uses the map to locate the 8 grid …
> Bug fix in the field map and G4 simulation performance improvement

- packages/reco/ktracker/SQReco.cxx
PR #82 added the output of Tracklet to the DST tree with can be enabled by `SQReco::set_enable_eval_dst(true)`. However in PR #82 only the global tracklets will be saved, which does not work if we would like to use partial track outputs produced while reconstructing cosmic ray muons. This PR addresses this problem. The changes are pretty minor, so I would like to have it merged before the end of the week so that people working on the hodoscope/dark photon/prop tube efficiency studies could use it for the official cosmic ray production.
> added additional eval list to the eval_ DST output

- packages/reco/ktracker/Fun4AllSRawEventInputManager.cxx
- packages/reco/ktracker/Fun4AllSRawEventInputManager.h
- packages/reco/ktracker/SQReco.cxx
In the past Haiwang implemented a Fun4AllSRawEventInputManager to read the E906-style ROOT data file which contains the SRawEvent, and add it to the DST tree. 
I added an option `Fun4AllSRawEventInputManager::enable_E1039_translation()` which is turned off by default. User can call this function to turn it on, then in addition to adding a `SRawEvent` node to the DST tree, the input manager will also use the information from `SRawEvent` to create `SQRun` and `SQSpillMap` node on the RUN tree, plus `SQEvent`, `SQHitVector`, `SQTriggerHitVector` on the DST tree.  The main purpose is to help people make analysis modules, in particular detector analysis modules for both E1039 and E906 in the same way.
Since this is turned off be default and does not alter the original behavior, it should have …
> Translation from E906 SRawEvent to E1039 DST-style data structure

- build.sh
- online/onlmonserver/OnlMonH4.cc
- online/onlmonserver/OnlMonHodo.cc
The time axis of the OnlMonHodo plots is now auto-adjusted so as to closely show all recorded hits.  This change was asked by the hodo experts, since the signal timing might change frequently in future trigger timing adjustments.  The new code is already running fine for the online decoding.
The new option (-b) of `build.sh` might be helpful to others, which let us put the `build` directory on a faster disk.
> Small change of OnlMonHodo tdcTime range

- packages/geom_svc/GeomSvc.cxx
- packages/geom_svc/GeomSvc.h
- packages/global_consts/GlobalConsts.h
- packages/reco/SQGenFit/GFFitter.cxx
- packages/reco/SQGenFit/GFMeasurement.cxx
- packages/reco/SQGenFit/GFMeasurement.h
- packages/reco/interface/FastTracklet.cxx
- packages/reco/interface/FastTracklet.h
- simulation/g4detectors/PHG4BlockSteppingAction.cc
This change does not introduce any real change, but in general some minor performance twist and code re-structure.
* in GeomSvc  unordered_map instead of map to store the wire position lookup table to achieve o(1) performance
* added more information in the G4Hit useful for EMCal study
* make all member functions const whenever possible in GFMeasurement and Tracklet class
* make GFFitter::processOneTrack return different exit code when encountered different failures to assist debugging
I have tested the change using Fun4Sim program, before and after the change yielded exactly the same output, as expected.
Obviously this PR is not in a hurry, and can be rolled out with the next big update.
> Performance optimization for the tracking-related code

- online/macros/Fun4MainDaq.C
- packages/db_svc/DbSvc.cc
Two small updates are included.  (1) `Fun4AllSpillDstOutputManager`, which outputs one DST file per spill group, is enabled in the online decoder.  The number of spills per DST is set to 100 now.  (2) The connection timeout was made longer (from 10 to 120 sec) in order to hopefully resolve the error in DbSvc::ConnectServer().
I cannot assure that the DbSvc error has been really resolved because the error was rare (0 in 10,000 trials) even without this update.  I expect to check it in the coming practical uses (simulation, decoding, etc.).
The updates are simple, and I have confirmed that the updated code can be compiled and run fine.  Thus I think Abi can just take a look and merge.
> DSTs per spill group and longer MySQL connection timeout

- build.sh
- framework/phool/recoConsts.cc
- packages/db_svc/DbSvc.cc
- packages/db_svc/DbSvc.h
- packages/geom_svc/GeomSvc.cxx
- packages/geom_svc/GeomSvc.h
- packages/geom_svc/macros/UploadCalibParam.C
- packages/geom_svc/macros/UploadChanMap.C
- packages/geom_svc/macros/UploadGeomParam.C
This PR makes the geometry info switchable.  I needed this switch when confirming that the track position dependence of the sagitta ratio observed by Dinupa was caused by the plane tilt angle.  It will be needed when we have multiple versions of the geometry info in the future.  The default geometry hasn't changed.
I first added three constants to `recoConsts`; `RUNNUMBER`, `DB_SERVER` and `DB_USER`.  I then modified `DbSvc`, which now uses `DB_SERVER` and `DB_USER` by default to select the server and the user of DB.  I also modified `GeomSvc` so that `initPlaneDbSvc()` now reads a run number from `RUNNUMBER` and initializes the plane position for the run (via `GeomParamPlane`).
The plane position per run range is given in `e1039-resource/geom/plane/run_range.tsv`.  It has not changed for …
> Switchable geometry info

- framework/phool/PHFlag.cc
- generators/PHPythia8/PHPythia8.C
- packages/dptrigger/DPTriggerAnalyzer.cxx
- packages/geom_svc/CMakeLists.txt
- packages/geom_svc/CalibParamXT.cc
- packages/geom_svc/CalibParamXT.h
- packages/geom_svc/GeomSvc.cxx
- simulation/g4detectors/CMakeLists.txt
- simulation/g4detectors/SQChamberRealization.cc
- simulation/g4detectors/SQChamberRealization.h
- simulation/g4detectors/SQChamberRealizationLinkDef.h
- simulation/g4detectors/SQDigitizer.cc
- simulation/g4detectors/SQDigitizer.h
- simulation/g4main/PHG4TruthSubsystem.cc
Two topics are included in this PR.
1. Management of simulation constants.  
I'm thinking a method of properly managing all simulation parameters, as presented in DocDB 9331.  The method proposed in this PR is to simply make use of `recoConsts`.  As a demonstration, I put several lines in `PHPythia8` etc. that add parameters to `recoConsts`.  The contents of `recoConsts` are expected to be written to a TSV file at the end of `Fun4Sim.C` etc. via `rc->WriteToFile("recoConsts.tsv")`.  If you are fine with this method, I will be adding more lines in a future.
2. Implementation of chamber realization.
I made a new SubsysReco module, `SQChamberRealization`.  Here I would propose to have this module outside `SQDigitizer`, because the chamber realization is sometimes re-done with different …
> Simulation constants and chamber realization

- packages/UtilAna/UtilDimuon.cc
- packages/UtilAna/UtilDimuon.h
- simulation/g4dst/CMakeLists.txt
- simulation/g4dst/LinkDef.h
- simulation/g4dst/SQGeomAcc.cc
- simulation/g4dst/SQGeomAcc.h
- simulation/g4dst/SQGeomAccLoose.cc
- simulation/g4dst/SQGeomAccLoose.h
This PR is to add a new SubsysReco module, `SQGeomAcc`, which is a more accurate/flexible version of `RequireParticlesInAcc`.
`SQGeomAcc` has a mode for muon condition.  The mode can be `SINGLE`, `SINGLE_T` (muon at top), `PAIR`, `PAIR_TBBT` (pair at T+B or B+T), etc.  `SQGeomAcc` also has a mode for planes that define the acceptance.  The mode can be either `HODO`, `CHAM` or `HODO_CHAM` (both).
`SQGeomAcc` uses `SQHit` to judge whether a track hits a plane, where `RequireParticlesInAcc` uses `G4Hit`.  Therefore `SQGeomAcc` is more accurate about the acceptance boundary, although it is slower since the digitization has to be always carried out.  `RequireParticlesInAcc` was renamed to `SQGeomAccLoose`.  It might be still useful since it is faster but might be deleted in future.
I modified …
> More accurate/flexible requirement of geometric acceptance

- framework/fun4all/SubsysReco.h
- generators/E906LegacyGen/SQPrimaryParticleGen.C
- generators/E906LegacyGen/SQPrimaryParticleGen.h
- generators/E906LegacyGen/macros/CheckParticleGenDrellYan.C
- generators/E906LegacyGen/macros/CheckParticleGenJPsi.C
- generators/E906LegacyVtxGen/SQPrimaryVertexGen.C
- generators/E906LegacyVtxGen/SQPrimaryVertexGen.h
- online/onlmonserver/OnlMonV1495.cc
- packages/UtilAna/UtilBeam.cc
- packages/db_svc/DbSvc.cc
- packages/geom_svc/GeomSvc.cxx
- simulation/g4dst/SQGeomAcc.h
- simulation/g4dst/SQGeomAccLoose.h
The primary update in this PR is that the E906 legacy generator now properly sets the absolute scale of the J/psi and psi' cross sections.  Attached is a plot of the J/psi cross section, drawn by a new test macro (`CheckParticleGenJPsi.C`).
I changed the cross-section unit from nb to pb returned by `SQPrimaryParticleGen` since pb is used by PYTHIA8.
I made `SQPrimaryParticleGen` and others output more parameters to `recoConsts`.
I also modified `DbSvc` so that it now tries the DB connection 5 times at max, because we saw the connection sometimes fails in the online decoding and the grid job.
> Absolute cross sections of J/psi and psi' by E906 legacy generator and more

- interface_main/SQMCEvent_v1.cxx
- online/decoder_maindaq/MainDaqParser.cc
- packages/db_svc/DbSvc.cc
- packages/reco/interface/FastTracklet.cxx
This PR includes four small changes.
1. The formula used in `FastTracklet::getCharge()` was modified in order to handle the anti-parallel magnet polarity.  It has been studied in DocDB 9505 and is explained in the Doxygen-style comment on the function.
2. The Main DAQ decoder temporarily skips the data from V1495 boards, because the data format is being changed because of the upgrade for the buffered readout.  After the upgrade is completed, the decoder will be modified again for the new data format.
3. The event weight in `SQMCEvent` is set to 1 by default.
4. `DbSvc` prints out a message when it retries a DB connection, for debugging purpose.
I have confirmed that the updated code can be built fine and is running fine for the online decoding.  The new charge formula has been tested by …
> New formula for tracklet charge and change in decoding v1495 data

- framework/phool/recoConsts.cc
- generators/E906LegacyGen/SQPrimaryParticleGen.C
- simulation/g4main/CMakeLists.txt
- simulation/g4main/PHG4ParticleGun.h
- simulation/g4main/PHG4SimpleEventGenerator.cc
- simulation/g4main/PHG4SimpleEventGenerator.h
This PR introduces mainly two updates on `PHG4SimpleEventGenerator`.
1. It creates the SQEvent and SQMCEvent nodes.  Particularly the run/spill/event IDs are now meaningful, which were always max. integer.
1. It sets `recoConsts` variables (like `PHG4SEG_EVENT_COUNT`) to record the number of generated events and the event-generator parameters.
There are two more small updates.
1. `SIGX_BEAM` in `recoConsts.cc` was changed to a realistic value (2.0 -> 0.3 cm).  I'd like to make all the values in `recoConsts.cc` realistic and remove the calls of `set_DoubleFlag()` etc. from `Fun4Sim.C`, in order to simplify the macro.  Do you think this course of action fine?
1. A potential problem in `SQPrimaryParticleGen::InitRun()` was fixed.  All the data nodes are now found or created regardless of the …
> Update on PHG4SimpleEventGenerator

- online/macros/Fun4MainDaq.C
- packages/Display/README.md
- packages/Display/interface/PHEventDisplay.cxx
- packages/Display/modules/mTrkEveDisplay.cxx
- packages/UtilAna/UtilOnline.cc
- packages/reco/interface/SRawEvent.h
- packages/reco/ktracker/Fun4AllSRawEventOutputManager.cxx
- packages/reco/ktracker/Fun4AllSRawEventOutputManager.h
- packages/reco/ktracker/Fun4AllSRawEventOutputManagerLinkDef.h
- packages/reco/ktracker/SQReco.cxx
- packages/reco/ktracker/TriggerAnalyzer.cxx
- packages/reco/ktracker/UtilSRawEvent.cxx
- packages/reco/ktracker/UtilSRawEvent.h
- simulation/g4detectors/PHG4EMCalDetector.cc
- simulation/g4eval/PHG4DSTReader.cc
This update is to introduce a spill-by-spill output of the decoded data for the online reconstruction.  The updated code is already running fine for the online decoding.
`Fun4AllSRawEventOutputManager` is the front end of the new output scheme.  It is enabled by default in the online decoding, i.e. `online/macros/Fun4MainDaq.C`.
The translation from SQEvent/Hit to SRawEvent will be useful for other classes.  Therefore I'd like to export the contents of `SQReco::BuildSRawEvent()` to a new namespace, `UtilSRawEvent`.  One problem here is that two member variables of `SQReco`, i.e. `_m_hitID_idx` and `_m_trghitID_idx`, cannot be handled by `UtilSRawEvent`.  But these variables seem not in use at present.  Can I remove them and use `UtilSRawEvent` in `BuildSRawEvent()`?
> Spill-by-spill SRawEvent output for online reconstruction

- simulation/README.md
- simulation/g4detectors/SQDigitizer.cc
- simulation/g4detectors/SQDigitizer.h
- simulation/g4main/HepMCNodeReader.cc
- simulation/g4main/HepMCNodeReader.h
Here is a small update to add switches for handling of simulated data.  I needed them to efficiently generate open-charm events.
`HepMCNodeReader` is already able to filter out particles by particle ID.  I added a function, `enable_position_filter(), to select particles by production position.  Using this function, we can have an event generator (like PYTHIA) produce muons and then `HepMCNodeReader` exclude muons produced behind FMag.
`SQDigitizer` doesn't digitize secondary particles by default.  I added a function, `set_digitize_secondaries()`, to change the behavior.
They won't change the default behavior of our simulation.  Thus this PR can be merged safely.
> Switches for filtering and digitization of simulated data

- generators/E906LegacyGen/SQPileupGen.C
- generators/E906LegacyGen/SQPrimaryParticleGen.C
- simulation/g4main/HepMCNodeReader.cc
- simulation/g4main/PHG4ParticleGeneratorBase.cc
- simulation/g4main/PHG4ParticleGeneratorVectorMeson.cc
- simulation/g4main/PHG4Reco.cc
- simulation/g4main/PHG4SimpleEventGenerator.cc
- simulation/g4main/SQCosmicGen.cc
Changed PHINEVENT from PHDataNode to PHIODataNode to make it more flexible to use in the DST level analysis (as found by discussion with Kenichi). Most of the changes are very small in the generator levels. I built the change successfully.
> changed PHG4INEVENT from PHDataNode to PHIODataNode

- macros/Fun4DumpGeom.C
- macros/G4_Beamline.C
- macros/G4_InsensitiveVolumes.C
- macros/G4_SensitiveDetectors.C
- macros/G4_Target.C
- online/onlmonserver/OnlMonCham.cc
Here are small changes to
1. Add the concrete block behind FMag to the insensitive volumes,
2. Add short Doxygen comments to `G4_*.C`, and
3. Change the range of the TDC time histograms in  `OnlMonCham`.
Lines 75-87 of `InsensitiveVolumes.C` are for the 1st change.  It is disabled by default at present, and thus won't affect any real/simulation result.  DarkQuest will test it first.  SpinQuest might enable it, after checking its effect.
The 3rd change is totally an additional one that I found necessary now.  The range was found too narrow and thus enlarged.
I have confirmed that the modified code can be built without error.
> Addition of concrete block behind FMag

- build.sh
- generators/E906LegacyGen/SQPileupGen.C
- generators/E906LegacyGen/SQPileupGen.h
- online/decoder_maindaq/MainDaqParser.cc
- online/decoder_maindaq/MainDaqParser.h
- packages/calibrator/CalibDriftDist.cc
- packages/calibrator/CalibDriftDist.h
- packages/geom_svc/RunParamBase.cc
- script/exec-decoder.sh
- script/setup-install.sh
I'd like to suggest a small update on SQPileupGen, together with other unrelated ones that I need now.
I added `_evt->set_qie_rf_intensity(0, QIEcount)` to `SQPileupGen.C`, which sets the QIE count to SQEvent.  It should be useful in comparing the piled-up events with the E906 NIM3 events etc.  I also changed `TH1D*` to `TH1*` in SQPileupGen, where we had better use the base class in general.
I modified the decoder (`MainDaqParser`), which now extracts the run-end time from the Coda End event.  The run-end time had been available but just not utilized by the decoder. 
I modified `CalibDriftDist` (and `RunParamBase`), which is now able to read a parameter set (i.e. chamber X-T curve) from a local file.  This function will be soon used by the calibration of the X-T curve using cosmic rays. …
> Small updates on SQPileupGen, MainDaqParser and CalibDriftDist

- build.sh
- online/onlmonserver/LinkDef.h
- online/onlmonserver/OnlMonMainDaq.cc
- online/onlmonserver/OnlMonParam.cc
- online/onlmonserver/OnlMonParam.h
- packages/evt_filter/E906SpillSelector.cxx
- packages/evt_filter/E906SpillSelector.h
- packages/evt_filter/E906SpillSelectorLinkDef.h
- packages/evt_filter/FilterByTrigger.cxx
- packages/evt_filter/FilterByTrigger.h
- packages/evt_filter/FilterByTriggerLinkDef.h
This PR is to add a new utility class, `OnlMonParam`, which handles run-dependent parameters for the OnlMon client.  It is used by `OnlMonMainDaq` for now, which reads the expected number (=83) of TDC boards read out per event, and makes a warning if the number is found different in runs/events.  Parameters are stored in TSV files under `/data2/e1039/onlmon/param/`, which can be modified by subsystem experts at anytime.
I also imported `E906SpillSelector` and `FilterByTrigger` from `e1039-analysis/GenRoadset/src/`.  They should be useful for other online/offline analyses when selecting events by spill IDs (of E906 data for now) and trigger bits.  We can add such general-purpose SubsysReco modules to `evt_filter/` in the future.
The updated code can be compiled fine.  I have confirmed that …
> Addition of OnlMonParam etc.

- build.sh
- framework/phool/recoConsts.cc
- generators/E906LegacyGen/SQPrimaryParticleGen.C
- online/decoder_maindaq/Fun4AllEVIOInputManager.cc
- packages/calibrator/CalibDriftDist.cc
- packages/reco/ktracker/EventReducer.cxx
- packages/reco/ktracker/EventReducer.h
- simulation/g4main/PHG4Reco.cc
- simulation/g4main/PHG4Reco.h
This PR includes two changes.
1. I modified `CalibDriftDist` (and `Fun4AllEVIOInputManager`).  It now reads the calibration parameter stored at `$E1039_RESOURCE/calib/xt_curve/20211222` (actually it reads a copy on MySQL DB) to update the drift distance, the in-time window and the element position of `SQHit`.  I dropped the 'e' option of `EventReducer` in order to make `CalibDriftDist` unique.  I plan to factor out other functions of `EventReducer`.
2. I added a new function, `PHG4Reco::set_field_map()`, which takes no argument.  It instead reads the parameters from `recoConsts`.  On the other hand, the existing function `set_field_map(const std::string &fmap, const PHFieldConfig::FieldConfigTypes dim)` requires the parameters to be written as string in each Fun4All macro, like …
> Arrangement of `CalibDriftDist`, `EventReducer` and `PHG4Reco`

- interface_main/SQHitVector.h
- interface_main/SQHitVector_v1.h
- online/decoder_maindaq/CodaInputManager.cc
- online/decoder_maindaq/CodaInputManager.h
- online/decoder_maindaq/DecoParam.cc
- online/decoder_maindaq/DecoParam.h
- online/decoder_maindaq/MainDaqParser.cc
- online/decoder_maindaq/MainDaqParser.h
- online/macros/Fun4MainDaq.C
- packages/calibrator/CalibDriftDist.cc
- packages/calibrator/CalibDriftDist.h
- packages/calibrator/CalibHodoInTime.cc
- packages/geom_svc/CalibParamXT.cc
- packages/geom_svc/CalibParamXT.h
- packages/geom_svc/macros/UploadCalibParam.C
- packages/geom_svc/macros/UploadChanMap.C
- packages/geom_svc/macros/UploadGeomParam.C
- packages/geom_svc/macros/upload-param.sh
- packages/reco/ktracker/SQReco.cxx
- script/exec-decoder.sh
- simulation/g4detectors/SQChamberRealization.cc
- simulation/g4detectors/SQChamberRealization.h
This update is primarily to enable the V1495 TDC readout of the Main DAQ decoder.  The present cosmic runs are being decoded by this updated version, and the online monitor is showing reasonable hit distributions.
This update also includes a change in the meaning of the chamber X-T curve parameter, which is handled by `CalibParamXT`.  Now its time (T) means the *TDC* time instead of the *drift* time, and the T range of the X-T curve is regarded as the in-time window.  `CalibParamInTimeTaiwan` now takes care of only the hodoscope parameters.  This new parameter handling should be easier to be maintained.  The parameter values under `e1039-resource` have been modified accordingly.
`SQChamberRealization` and `CalibDriftDist` were modified to use the updated `CalibParamXT` properly. …
> Updates on Main DAQ decoder, chamber X-T curve and chamber realization

- online/decoder_maindaq/Fun4AllEVIOInputManager.cc
- packages/calibrator/CalibDriftDist.cc
- packages/calibrator/CalibDriftDist.h
- packages/geom_svc/GeomSvc.h
- packages/reco/interface/FastTracklet.cxx
- packages/reco/ktracker/KalmanFastTracking.cxx
- packages/reco/ktracker/KalmanFastTracking.h
- packages/reco/ktracker/KalmanFastTrackletting.cxx
- packages/reco/ktracker/KalmanFastTrackletting.h
- packages/reco/ktracker/SQReco.cxx
- packages/reco/ktracker/SQReco.h
- packages/reco/ktracker/SQTrackletReco.cxx
- packages/reco/ktracker/SQTrackletReco.h
- packages/reco/ktracker/SQTrackletRecoLinkDef.h
- script/exec-decoder.sh
This update is to introduce a modified version of kTracker that reconstructs local tracklets using drift distance.  It is helpful in calibrating the X-T curve using cosmic data.  I'd like to first hear your opinions about the concept+method of this update.  If it looks fine, I will straighten up the code and ask you a closer review.
The original tracklet reconstruction (i.e. `KalmanFastTracking::buildTrackletsInStation()`) ignores the drift distance, as the drift sign of hits is not resolved at that stage.  Thus I created new classes; `SQTrackletReco` and `KalmanFastTrackletting`, by inheriting them from `SQReco` and `KalmanFastTracking`.  `KalmanFastTrackletting` takes all combinations of drift signs to reconstruct D3, D2 and D2+D3 tracklets.
`SQReco` and `KalmanFastTracking` were …
> Modified version of kTracker for local-tracklet reconstruction

- online/decoder_maindaq/Fun4AllSpillDstOutputManager.cc
- online/decoder_maindaq/Fun4AllSpillDstOutputManager.h
- online/macros/Daemon4MainDaq.C
- online/macros/Fun4MainDaq.C
- packages/db_svc/DbSvc.h
- script/exec-decoder.sh
- script/setup-install.sh
`Fun4AllSpillDstOutputManager` is the Fun4All output manager that is outputting spill-DSTs (one file per 100 spills by default).  This update makes the manager record the status of each spill DST on MySQL DB.  The record can be used by the semi-online reconstruction to launch a job once each spill DST gets ready.
Below is an example of the DB table.  "status = 1" means the output of each spill DST has started, and "status = 2" means it has finished.  
```
select * from user_e1039_maindaq.spill_dst_status;
+--------+----------------+---------------+------------------------------------------------------------------+--------+------------+------------+
| run_id | spill_id_first | spill_id_last | file_name                                                        | status | utime_b    | utime_e …
```
> Status of spill-DST output on DB

- packages/kTThreads/KScheduler.cxx
- packages/kTThreads/KScheduler.h
- packages/kTThreads/macros/AnaData.C
- packages/kTThreads/macros/README.md
- packages/kTThreads/macros/RecoData.C
- packages/kTThreads/macros/exec_ana.sh
- packages/kTThreads/macros/exec_reco.sh
- packages/kTThreads/macros/setup.sh
- packages/kTThreads/macros/watch_deco_data.sh
- packages/kTThreads/macros/watch_reco_data.sh
This update is to modify and add functions of kTThreads so that the online reconstruction can keep running for the cosmic data. 
The key changes are
* Set `NTHREADS` to 16 (it seems valid according to "top"),
* Made `KScheduler::Init()` so that we can change some configurations before the initialization, and
* Used `KalmanFastTrackletting` instead of `KalmanFastTracking`, in order to reconstruct and store local tracklets.
Shell scripts and ROOT macros were added to `macros/`, which can be used to automatically launch the reconstruction per online data file.  They also launch an analysis program that extracts a set of parameters from reconstructed data for the monitoring purpose.
The modified code can be built fine and is running on `e1039trackcpu`.  It does not affect any other program, …
> Configuration of kTThreads for online cosmic data

- framework/phool/recoConsts.cc
- online/decoder_maindaq/MainDaqParser.cc
- online/decoder_maindaq/MainDaqParser.h
- online/macros/Fun4MainDaq.C
- packages/Display/interface/EventDispUI.h
- packages/PHField/PHFieldSeaQuest.cc
This PR includes two updates.
1. 
The KMag z-position was found incorrect, which should have been taken from an old E906 code.  It was corrected (from 1064.26 to 1042.01722 cm) in `recoConsts.cc`.  Also `PHFieldSeaQuest.cc` was modified not to use the hard-coded value in  it.
I added to `recoConsts::init(runNo)` the default parameter set for the E906 Run-6 data.  I plan to use this way of integrating all parameter sets for E1039 datasets.
2.
The Main-DAQ decoder was modified so that it can skip words from ROC or event in case of word-format errors, instead of discarding the whole event.  The modified code has already been used for the online decoding.
> Correct KMag position and better decoding error handling

- framework/fun4all/Fun4AllServer.cc
- simulation/g4main/PHG4EtaPhiParameterization.cc
I built e1039-core on UVA Rivanna, and found these changed needed.  They should be due to a difference in gcc versions.
> Small fixes to resolve errors that occured at UVA Rivanna.

- framework/phool/recoConsts.cc
- packages/geom_svc/GeomSvc.cxx
- packages/geom_svc/GeomSvc.h
- script/setup-install.sh
This update is mainly to add a method of manually selecting the plane geometry version.  Usually the plane geometry is selected based on the `RUNNUMBER` flag.  But if the `GeomPlane` flag exists (before instantiating `GeomSvc`) the ID given by `GeomPlane` is selected.
> Manual selection of plane geometry version.

- framework/fun4all/Fun4AllServer.cc
- framework/fun4all/Fun4AllServer.h
- online/macros/Fun4MainDaq.C
- online/onlmonserver/OnlMonServer.cc
This update is to fix a problem that the OnlMonServer sometimes becomes unavailable.  OnlMonServer doesn't suicide the server process if its run number is larger than the one that sends the suicide request.
> Change in the condition when OnlMonServer suicides

- build.sh
- framework/phool/recoConsts.cc
- online/decoder_maindaq/DecoData.h
- online/decoder_maindaq/DecoParam.h
- online/decoder_maindaq/Fun4AllEVIOInputManager.cc
- online/decoder_maindaq/Fun4AllEVIOInputManager.h
- online/decoder_maindaq/MainDaqParser.cc
- online/decoder_maindaq/MainDaqParser.h
- online/macros/Fun4MainDaq.C
- packages/geom_svc/ChanMapV1495.cc
- packages/geom_svc/ChanMapV1495.h
- packages/reco/ktracker/Fun4AllSRawEventOutputManager.cxx
- packages/reco/ktracker/Fun4AllSRawEventOutputManager.h
The following changes were made to be used for the beam commissioning;
* The spill ID given by the spill counter is used by default.
* The status of spill-by-spill SRawEvent output files is written to MySQL DB.
* The mapping for V1495 TDC was updated.
* The Coda event count is saved in DST (instead of coda ID). 
The updated version is running fine for the online decoding.
> Updates for commissioning

- interface_main/SQRun.h
- interface_main/SQRun_v2.cxx
- interface_main/SQRun_v2.h
- interface_main/SQRun_v2LinkDef.h
- online/decoder_maindaq/CalibMergeH4.cc
- online/decoder_maindaq/CodaInputManager.h
- online/decoder_maindaq/DbUpRun.cc
- online/decoder_maindaq/DbUpRun.h
- online/decoder_maindaq/DecoData.cc
- online/decoder_maindaq/DecoData.h
- online/decoder_maindaq/Fun4AllEVIOInputManager.cc
- online/decoder_maindaq/Fun4AllEVIOInputManager.h
- online/decoder_maindaq/Fun4AllTriggerDstOutputManager.cc
- online/decoder_maindaq/Fun4AllTriggerDstOutputManager.h
- online/decoder_maindaq/Fun4AllTriggerDstOutputManagerLinkDef.h
- online/decoder_maindaq/MainDaqParser.cc
- online/decoder_maindaq/MainDaqParser.h
- packages/Display/interface/EventDispUI.cxx
- packages/Display/interface/EventDispUI.h
- packages/UtilAna/UtilOnline.cc
- packages/UtilAna/UtilOnline.h
- packages/calibrator/CalibHitElementPos.cc
- packages/calibrator/CalibHitElementPos.h
- packages/calibrator/CalibHodoInTime.cc
- packages/geom_svc/GeomSvc.cxx
- packages/geom_svc/GeomSvc.h
- packages/reco/interface/SRawEvent.cxx
- packages/reco/interface/SRawEvent.h
I made multiple changes to meet our needs during the commissioning.  The updated version has been running fine for the online Main-DAQ decoding.
* Added DP-hodo hits to the SRawEvent output file.
* Updated the 3D event display to handle the spill-level DST. 
* Updated the decoder to read the V1495 version information.  Made `SQRun_v2` to store it.
* Added Fun4AllTriggerDstOutputManager, to record NIM4 events in dedicated files. 
* Changed the handling of spill ID in the Main-DAQ decoder.  When the spill counter event is not available for a spill, the spill is given an incremental ID (which was always 0 in the previous version).
* Changed the behavior of CalibHodoInTime, so that it doesn't touch unmapped channels. 
* Added `isInh()` to `GeomSvc`. 
* Add functions to `UtilOnline` to handle …
> Development for beam commissioning

- packages/UtilAna/LinkDef.h
- packages/UtilAna/TrigRoad.cc
- packages/UtilAna/TrigRoad.h
- packages/UtilAna/TrigRoads.cc
- packages/UtilAna/TrigRoads.h
- packages/UtilAna/TrigRoadset.cc
- packages/UtilAna/TrigRoadset.h
This update is just to add utility classes (`UtilTrigger::TrigRoadset` etc.) that handle the trigger roadset.  A key feature is that `TrigRoadset::LoadConfig()` accepts a roadset ID or a pair of LBTop and LBBot IDs to load the corresponding configuration file under `$E1039_RESOURCE/trigger/rs`.
`DPTriggerAnalyzer` can handle the trigger roadset, but it assumes that the configuration file is in a special line format.  Thus I plan to obsolete it.
`ktracker/TriggerAnalyzer` also can handle the trigger roadset, but is entangled with the tracking code where the trigger is independent of the tracking in principle.  I plan to replace/merge it with `UtilTrigger::TrigRoadset`.
I have confirmed that the updated code can be built fine and works as expected (using `e1039-analysis/RecoData2024`).
> Addition of utility classes to handle trigger roadset

- framework/phool/recoConsts.cc
- packages/reco/SQGenFit/GFField.cxx
- packages/reco/SQGenFit/GFField.h
- packages/reco/SQGenFit/GFTrack.cxx
- packages/reco/interface/SRecEvent.cxx
- packages/reco/interface/SRecEvent.h
- packages/reco/ktracker/SQVertexing.cxx
- packages/reco/ktracker/SQVertexing.h
- packages/reco/ktracker/SQVertexingLinkDef.h
I created a new package in ```packages/reco/ktracker``` named ```SQVertexing``` to handle the vertex finding and dimuon vertex fitting. 
The primary usage is like this:
```
SQVertexing* vertex = new SQVertexing();
//Choose to save the output dimuons inside SRecEvent (if true), or in a Fun4All container (if false), default is false
vertex->set_legacy_rec_container(false); 
//Choose to update the target swim results with the ones after applying track refitting, default is false
vertex->set_single_retracking(false);
//Specify the input file name for ROOT geometry, only needed if it's run without track reconstruction, i.e. run without SQReco in the module list
vertex->set_geom_file_name("filename_for_ROOT_geometry.root")
se->registerSubsystem(vertex);
```
Under the hood, the primary change …
> New SQVertexing package to (hopefully) handle dimuon vertexing correctly

- online/macros/Fun4MainDaq.C
- packages/reco/ktracker/Fun4AllSRawEventOutputManager.cxx
- packages/reco/ktracker/Fun4AllSRawEventOutputManager.h
- packages/reco/ktracker/Fun4AllSpillSRawEventOutputManager.cxx
- packages/reco/ktracker/Fun4AllSpillSRawEventOutputManager.h
- packages/reco/ktracker/Fun4AllSpillSRawEventOutputManagerLinkDef.h
- packages/reco/ktracker/SQVertexing.cxx
- packages/reco/ktracker/UtilSRawEvent.cxx
This pull request includes multiple updates eventually.
1. SQVertexing was found not converged on some events of the commissioning data.  To avoid it, we added lines to `SQVertexing::calcZsclp()` to enforce the valid momentum range, and also added the max number of iterations to `SQVertexing::refitTrkToVtx()`.  Verbose messages were added for debugging.
2. `Fun4AllSRawEventOutputManager` was renamed as `Fun4AllSpillSRawEventOutputManager` because it outputs spill-by-spill files.  A new manager, `Fun4AllSRawEventOutputManager`, was made, which outputs one file per process (=run).
3. A bug about the trigger bits in `UtilSRawEvent::SetEvent()` was fixed.  The order of FPGA and NIM bits in `SRawEvent` is different from that in `SQEvent`, but the function above had assumed that it is …
> Updates on SQVertexing, Fun4AllSRawEventOutputManager and UtilSRawEvent

- packages/reco/ktracker/SQVertexing.cxx
- packages/reco/ktracker/SQVertexing.h
This PR made two changes:
1. It added additional Boolean flags (and associated set functions) to allow user to control whether to use legacy-style input/output containers separately. ```SQVertexing::set_legacy_in_container()``` will switch between using ```SQTrackVector``` and old ```std::vector<SRecTrack>``` embedded inside the ```SRecEvent``` as input. Similarly,  ```SQVertexing::set_legacy_out_container()``` will switch between using ```SQDimuonVector``` and old ```std::vector<SRecDimuon>```  embedded inside the ```SRecEvent``` as output. Setting ```SQVertexing::set_legacy_container()``` will turn on/off both input and output switch simultaneously. 
2. Added some code at the end of ```SQVertexing::processOneDimuon()``` to change the sign of the Px of the "positive" muon if we are …
> Add flexibility in SQVertexing IO options

- packages/reco/SQGenFit/GFTrack.cxx
- packages/reco/ktracker/KalmanFastTracking.cxx
- packages/reco/ktracker/KalmanFastTracking.h
- packages/reco/ktracker/SQTrackletFitter.cxx
- packages/reco/ktracker/SQTrackletFitter.h
- packages/reco/ktracker/SQVertexing.cxx
This PR includes three small changes.
1. Take the tracklet fitter out of KalmanFastTracking and put it in its own class, so that other packages can use it. This is needed for the alignment code package;
2. Fixed a bug in GFTrack that sometimes the global constants are not properly initialized
3. Fixed a bug in SQVertexing. Now the Genfit unitlities are initialized if SQReco is not created.
> Minor bug fixes and re-org in various reconstruction code

- packages/reco/SQGenFit/GFTrack.cxx
- packages/reco/interface/SRecEvent.cxx
- packages/reco/interface/SRecEvent.h
- packages/reco/ktracker/SQVertexing.cxx
This is to fix a problem that SQVertexing outputs a different/strange vertexing result when it is used alone (i.e. without SQReco).  One clear failure was seen on the matrix inversion made in "GFTrack::updatePropState()".  It was because the beam covariance matrix was zero, and the root cause was that GFTrack was initialized only in the default constructor.  The default constructor is called only in SQReco, thus this problem was not apparent.
> Initialization of GFTrack

- packages/reco/ktracker/SQVertexing.cxx
- packages/reco/ktracker/SQVertexing.h
We now use a random generator (TRandom2) to select which muon we choose to flip the sign of Px when processing like-sign dimuons, because apparently the track list is pre-sorted by track quality (reduced chi2) thus creating a bias.
> Fixed the bias in always selecting mu+ for Px sign flip in like-sign dimuon processing

- interface_main/SQHitVector.h
- packages/calibrator/CalibDriftDist.cc
- packages/calibrator/CalibDriftDist.h
- packages/calibrator/CalibHodoInTime.cc
- packages/calibrator/CalibHodoInTime.h
This update is to add options to `CalibHodoInTime` and `CalibDriftDist` about hit removal.  They will be able to delete out-of-time hits when `DeleteOutTimeHit()` is called.  They will be able to also skip the calibration when `SkipCalibration()` is called, so that they can only delete out-of-time hits using the existing in-time flag of SQHits.
The default behaviors of  `CalibHodoInTime` and `CalibDriftDist` haven't changed.  
`SQHitVector.h` was modified to suppress the compilation warning about `return HitVector().end()`.
> Removal of out-of-time hits by `CalibHodoInTime` and `CalibDriftDist`

- build.sh
- generators/SingleMuonGen/CMakeLists.txt
- generators/SingleMuonGen/SQSingleMuonGen.cxx
- generators/SingleMuonGen/SQSingleMuonGen.h
- generators/SingleMuonGen/SQSingleMuonGenLinkDef.h
- generators/SingleMuonGen/SQSingleMuonTruthInfo.cxx
- generators/SingleMuonGen/SQSingleMuonTruthInfo.h
- generators/SingleMuonGen/SQSingleMuonTruthInfoLinkDef.h
A quick version of a single muon generator. The pion momentum and pT distributions are digitized from this paper https://arxiv.org/pdf/1404.5882. The pion is sequentially decayed to muons. A new Truth Information (SQSingleMuonTruthInfo) node is added to contain the generator level information.
> Single Muon Generator

- packages/geom_svc/GeomSvc.cxx
- packages/geom_svc/GeomSvc.h
This update is to fix a bug in `GeomSvc::initWireLUT()`.  This function should be called when some parameter is changed, like done in `setDetectorX0()`.  But the old values stored in private variables like `map_wirePosition` had not been cleared.  Thus some lines were added to clear them.  I have confirmed that, using `printTable()` and `printWirePosition()`, the values are changed.
> Bug fix in GeomSvc::initWireLUT().

- simulation/g4detectors/PHG4EMCalDetector.cc
- simulation/g4detectors/SQDigitizer.cc
PR to fix two issues in the current EMCal simulation. 
- First one is on the EMCal geometry, since the unit is already specified in the constructor, adding another unit would cause the geometry to be wrong by one order of magnitude.
- Second is on the energy deposit of EMCal hit. Without setting to zero, it would be randomly initialized, causing some undefined behaviors.
The fixes have been tested multiple times for the EMCal simulations for dark sector. Made this PR for synchronization with the master branch. PR should not affect anything except EMCal.
> EMCal bug fix

- packages/RUS/Fun4AllRUSOutputManager.cc
- packages/RUS/Fun4AllRUSOutputManager.h
This version adds variables from the true track information using the `SQTrack` class node. In addition to including the `trackID` in the true track label, the `trackID` is also added to the hit label. The name of the variable is `hit_trackID`.
In a Fun4All macro, the output manager should work for both simulation and experimental data. For this version, the `processID` is set manually. I will update this in the next version by setting those variables automatically by parsing the SQ nodes inside `Fun4AllRUSOutputManager`.
- DY = 11 (mu⁺)
- J/psi = 12 (mu⁺)
- psi′ = 13 (mu⁺)
- Single muon = 14
For the corresponding mu⁻ particle, the `processID` is set as +10 the above value.
The process ID in the hit label is encoded along with the source flag using the following logic:
```cpp
// Encoding …
```
>  adding true track variables in the RUS output file

- generators/SingleMuonGen/SQSingleMuonGen.cxx
- generators/SingleMuonGen/SQSingleMuonGen.h
- packages/reco/SQGenFit/GFTrack.cxx
- packages/reco/SQGenFit/GFTrack.h
- packages/reco/ktracker/SQVertexing.cxx
- packages/reco/ktracker/SQVertexing.h
This PR consists of three changes. 
The first commit changes the single muon generator to read X_BEAM and Y_BEAM reco consts when generating the primary vertex. In the past the primary vertex X and Y positions are hard-coded to be 0.
The second and third commit moves the single muon vertexing code from SQGenFit::GFTrack::getSRecTrack to SQVertexing::processOneMuon. In the past the single muon vertexing is done in SQGenFit::GFTrack::getSRecTrack which is called by SQReco. After we update the X_BEAM and Y_BEAM information and re-run the production with only SQVertexing the single muon info will not be updated.
The last commit added an error count data member is SQGenFit::GFTrack to supress the excessive error message in the extrapolation. Now the code will suppress future error messages …
> Small changes in Single Muon generator, added single muon vertexing
