build.sh, database/PHParameter/CMakeLists.txt, database/pdbcal/base/CMakeLists.txt, database/pdbcal/base/PdbRootify.pl, generators/PHPythia8/CMakeLists.txt, generators/phhepmc/CMakeLists.txt, packages/Half/CMakeLists.txt, packages/PHGeometry/CMakeLists.txt, packages/ktracker/KalmanFastTrackingWrapper.cxx, packages/ktracker/KalmanFastTrackingWrapper.h, packages/ktracker/KalmanPrgTrk.cxx, packages/ktracker/KalmanPrgTrk.h, packages/vararray/CMakeLists.txt, simulation/g4decayer/CMakeLists.txt, simulation/g4detectors/CMakeLists.txt, simulation/g4dst/CMakeLists.txt, simulation/g4eval/CMakeLists.txt, simulation/g4gdml/CMakeLists.txt, simulation/g4main/CMakeLists.txt
Also modified the 'build.sh' macro.
Packages need to be compiled following the sequence in the 'build.sh' macro.
`./build.sh` to compile all packages in correct sequence.
`./build.sh <package-name>` to compile a specific package
=> CMake files added for all packages.

framework/ffaobjects/CMakeLists.txt, framework/fun4all/CMakeLists.txt, interface_main/CMakeLists.txt, interface_main/SQHit.h, interface_main/SQMCHit_v1.cxx, interface_main/SQMCHit_v1.h
Removed PHG4Hit keytype dependent in interface_main and added MY_INSTALL support.
=> Remove PHG4Hit keytype dependent in interface and add MY_INSTALL feature

build.sh, online/decoder_maindaq/CMakeLists.txt
- remove the libevent dependency from the decoder_maindaq as it is not used now
- changed the sequence of packages in build.sh so it runs successfully from scratch, which takes about 3'40'' on seaquestgpvm01
=> Small fix on compiling

generators/phhepmc/CMakeLists.txt, simulation/g4detectors/CMakeLists.txt, simulation/g4eval/CMakeLists.txt, simulation/g4main/CMakeLists.txt
Small changes needed to run the Fun4TrkDev.C macro in ROOT6
=> For macros to run in ROOT6

macros/Fun4MainDaq.C, online/chan_map/RunParamBase.cc, online/decoder_maindaq/CodaInputManager.cc, packages/db_svc/DbSvc.cc
I made this change as pointed out by Haiwang in PL #22.
=> I changed "/data2" to "/seaquest".

packages/geom_svc/GeomSvc.cxx
As discussed at the software/simulation meeting.
=> I added a bunch of name-vs-ID relations to the detector map.

macros/Fun4MainDaq.C, macros/OnlMon4MainDaq.C
=> ROOT5 compatible macro

online/onlmonserver/OnlMonCanvas.cc, online/onlmonserver/OnlMonClient.cc
Seems unable to compile without these includes on gpvm01.
=> Include fix

packages/db_svc/DbSvc.cc
Alternative interface for CalibDB config.
Using $E1039_RESOURCE to locate the conf.
=> Alternative interface for CalibDB config.

packages/Display/display/CMakeLists.txt, packages/Display/display/PHEveDisplay.cxx, packages/Display/display/PHEveDisplay.h, packages/Display/interface/CMakeLists.txt, packages/Display/interface/PHEventDisplay.cxx, packages/Display/interface/PHEventDisplay.h, packages/Display/interface/PHEventDisplayLinkDef.h, packages/Display/macro/Fun4All_EventDisplay.C, packages/Display/modules/CMakeLists.txt, packages/Display/modules/mPHEveModuleBase.h, packages/Display/modules/mTrkEveDisplay.cxx, packages/Display/modules/mTrkEveDisplay.h, simulation/g4detectors/PHG4E1039InsensDetector.cc
A first working (interactively) event display based on TEve.
Accompanied macros: [e1039-analysis/SimChainDev](https://github.com/E1039-Collaboration/e1039-analysis/tree/master/SimChainDev)
Display
- geometry
- fired wires
- reconstructed tracks
3D view:
Station view:
Hodo view:
Adding some simple buttons:
=> Event display based on TEve

online/chan_map/RunParamBase.cc, online/decoder_maindaq/CodaInputManager.cc, online/decoder_maindaq/DbUpRun.cc, online/decoder_maindaq/Fun4AllEVIOInputManager.cc, online/decoder_maindaq/MainDaqParser.cc, online/decoder_maindaq/UtilOnline.cc, online/decoder_maindaq/UtilOnline.h, online/macros/Daemon4MainDaq.C, online/macros/OnlMon4MainDaq.C, online/onlmonserver/LinkDef.h, online/onlmonserver/OnlMonCanvas.cc, online/onlmonserver/OnlMonCham.h, online/onlmonserver/OnlMonClient.cc, online/onlmonserver/OnlMonClient.h, online/onlmonserver/OnlMonHodo.h, online/onlmonserver/OnlMonMainDaq.h, online/onlmonserver/OnlMonProp.h, online/onlmonserver/OnlMonServer.cc, online/onlmonserver/OnlMonServer.h, online/onlmonserver/OnlMonTrigSig.h, online/onlmonserver/OnlMonUI.cc, online/onlmonserver/OnlMonUI.h, online/onlmonserver/OnlMonV1495.h, script/setup-install.sh, script/this-core-org.sh
I made various updates to improve the stability of the online decoding.  I changed also some default settings about data & parameter files to match with the real situation.
This version is not yet complete, as for example the auto-cycle mode of the online monitor always crashes.  But the problem is isolated in the online part.
=> Updates for better stability of online decoding.

packages/Display/display/PHEveDisplay.cxx, packages/Display/display/PHEveDisplay.h, packages/Display/modules/mTrkEveDisplay.cxx, packages/Display/modules/mTrkEveDisplay.h, packages/geom_svc/CMakeLists.txt, packages/geom_svc/GeomSvc.cxx, simulation/g4detectors/DPDigitizer.cc
- small linking fix
- add DP to default sim list
=> small fix and default setting

generators/E906LegacyGen/CMakeLists.txt, generators/E906LegacyGen/SQPrimaryParticleGen.C, generators/E906LegacyGen/SQPrimaryParticleGen.h, generators/E906LegacyGen/SQPrimaryVertexGen.C, generators/E906LegacyGen/SQPrimaryVertexGen.h
Added interfaces:
-beam profile for SQPrimaryVertexGen  <br />
-xF and m range for the SQPrimaryParticleGen  <br />
Also, fixed the bug related to the LHAPDF in CMake file
=> Added some interface for the E906LegacyGen

build.sh, framework/fun4all/Fun4AllDstOutputManager.cc, framework/fun4all/Fun4AllDstOutputManager.h, framework/phool/PHNodeIOManager.cc, framework/phool/PHNodeIOManager.h, online/decoder_maindaq/CodaInputManager.cc, online/decoder_maindaq/CodaInputManager.h, online/decoder_maindaq/MainDaqParser.cc, online/decoder_maindaq/MainDaqParser.h, online/macros/Fun4MainDaq.C, packages/Display/README.md, packages/Display/interface/EventDispUI.cxx, packages/Display/interface/EventDispUI.h, packages/Display/interface/EventDispUILinkDef.h, packages/Display/interface/PHEventDisplay.cxx, packages/Display/interface/PHEventDisplay.h, packages/Display/macro/EventDisp4MainDaqDst.C, packages/Display/macro/G4_SensitiveDetectors.C, packages/Display/macro/G4_Target.C, packages/Display/macro/exec-eve-disp.sh, packages/Display/macro/run6_data.opts, packages/Display/modules/CMakeLists.txt, packages/Display/modules/EvtDispFilter.cxx, packages/Display/modules/EvtDispFilter.h, packages/Display/modules/EvtDispFilterLinkDef.h, packages/UtilAna/UtilOnline.cc, packages/UtilAna/UtilOnline.h, script/exec-decoder.sh, script/setup-install.sh
Technical details were described in DocDB 7302 and presented on 03 Feb.  After the presentation, the interface of the original mode (`e1039-analysis/CODAChainDev`) has been unified into that of the new (=online) mode.
=> Real-time (=online) mode of the TEve-based event display.

build.sh, online/onlmonserver/OnlMonComm.cc, script/exec-decoder.sh, script/setup-install.sh
I forgot to commit these updates.  I have fixed a small bug fix in "OnlMonComm.cc", which makes the OnlMon viewer dead when the OnlMon server is not running.  I have added a new host name in several shell scripts since `seaquestdaq01` was renamed to `e1039prod1`.
=> Small updates on Main DAQ decoder.

generators/E906LegacyGen/SQBeamlineObject.C, generators/E906LegacyGen/SQPrimaryParticleGen.C, generators/E906LegacyGen/SQPrimaryVertexGen.C, packages/global_consts/GlobalConsts.h
Changed the Z_TARGET position and added Random seed in E906LegacyGen
=> Legacy abi

.gitignore
added build directory to gitignore list
=> added build directory to gitignore list

packages/UtilAna/LinkDef.h, packages/UtilAna/UtilDimuon.cc, packages/UtilAna/UtilDimuon.h, packages/UtilAna/UtilSQHit.cc, packages/UtilAna/UtilSQHit.h, packages/UtilAna/UtilTrack.cc, packages/UtilAna/UtilTrack.h, packages/UtilAna/UtilTrigger.cc, packages/UtilAna/UtilTrigger.h
Here I am adding classes/functions to`packages/UtilAna/`.  For example
* `UtilDimuon::FindDimuonByID()` finds a dimuon by its ID (not array index) from `SQDimuonVector`.
* `UtilTrack::FindHitsOfTrack()` finds all hits that are associated with a track.
If you have an idea of any other useful functions, I can add such this time.  Since the new classes/functions do not change the default behavior of `e1039-core`, I expect you could merge this PR after taking a brief look at the changes.
=> Addition of utility functions.

online/decoder_maindaq/MainDaqParser.cc, online/macros/Fun4MainDaq.C, online/macros/OnlMon4MainDaq.C, online/onlmonserver/LinkDef.h, online/onlmonserver/OnlMonCanvas.cc, online/onlmonserver/OnlMonCanvas.h, online/onlmonserver/OnlMonCham.cc, online/onlmonserver/OnlMonH4.cc, online/onlmonserver/OnlMonHodo.cc, online/onlmonserver/OnlMonMainDaq.cc, online/onlmonserver/OnlMonProp.cc, online/onlmonserver/OnlMonQie.cc, online/onlmonserver/OnlMonQie.h, online/onlmonserver/OnlMonReco.cc, online/onlmonserver/OnlMonTrigNim.cc, online/onlmonserver/OnlMonTrigSig.cc, online/onlmonserver/OnlMonV1495.cc, packages/UtilAna/LinkDef.h, packages/UtilAna/UtilBeam.cc, packages/UtilAna/UtilBeam.h
Here I added a new OnlMon client for QIE since the QIE TDC board was mounted on ROC and started being read out last week. The new version is already running online and will output contents in OnlMon plots once the board starts sending out data, as Zong-Wei reported in DocDB 9277.
I expect this pull request could be merged just after you shortly review the changes, because the new version is already running and does not affect other online/offline uses.
=> Addition of OnlMon client for QIE.

generators/PHPythia8/PHPythia8.C
small bug due to the difference not being able to catch by GitHub
=> small bug to include header file

online/macros/TestOnlMonClient.C, online/onlmonserver/OnlMonTrigSig.cc, online/onlmonserver/README.md, packages/UtilAna/UtilOnline.cc, packages/UtilAna/UtilOnline.h, script/setup-install.sh
This update is to start a new procedure for developing OnlMonClient.  The FPGA trigger group plans to use it soon.
Basically macros and documents were modified.  Thus no online/offline output will be affected.  I have confirmed that the updated code can be built and run fine (using run 3620).
=> New procedure for developing OnlMonClient

framework/phool/recoConsts.cc, packages/reco/ktracker/KalmanFastTracking.cxx
Temporary solution to disable muon ID, should develop a more robust muon ID program in the future
=> Added a REQUIRE_MUID flag to enable/disable prop tube segments for now
